package gov.unb.cic.ed.trabalhopilhaed;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class ExpressaoGUI extends javax.swing.JFrame {

    public ExpressaoGUI() {
        initComponents();

        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        this.setLocation(x, y);

        txtExpressao.setText("");
        lblPosfixa.setText("");
        lblResultado.setText("");

        txtExpressao.getDocument().addDocumentListener(new DocumentListener() {

            public void changedUpdate(DocumentEvent e) {
                avaliar();
            }

            public void removeUpdate(DocumentEvent e) {
                avaliar();
            }

            public void insertUpdate(DocumentEvent e) {
                avaliar();
            }
        });
    }

    private void avaliar() {
        ExpressaoAritmetica e = new ExpressaoAritmetica();

        lblResultado.setText("");
        lblPosfixa.setText("");

        Logger.getLogger(ExpressaoGUI.class.getName()).log(Level.INFO, null, "Expressão: " + txtExpressao.getText());

        if (txtExpressao.getText().isEmpty()) {
            return;
        }

        e.setExpressao(txtExpressao.getText().replaceAll(" ", "").toUpperCase());
        if (!e.isExpressaoValida()) {
            lblResultado.setText("Expressão inválida.");
            return;
        }
        
        try {
            e.validarVariavel();
            lblPosfixa.setText(e.getPosfixa(true));
            return;
        } catch (Exception ex) {
            //Nao faz nada, tenta processar como valores
        }
        
        try {
            lblPosfixa.setText(e.getPosfixa(false));
            lblResultado.setText(Integer.toString(e.avaliar()));
        } catch (Exception ex) {
            //Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex.getMessage());
            lblResultado.setText("Erro: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtExpressao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblPosfixa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        txtExpressao.setText("?????????");
        getContentPane().add(txtExpressao);
        txtExpressao.setBounds(190, 290, 308, 28);

        jLabel1.setText("Notação posfixa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 330, 152, 14);

        lblPosfixa.setText("????????????????????");
        getContentPane().add(lblPosfixa);
        lblPosfixa.setBounds(190, 330, 308, 16);

        jLabel7.setText("Valor:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 360, 36, 16);

        lblResultado.setText("??????????");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(190, 360, 300, 16);

        jLabel2.setText("Expressão:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 300, 68, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Universidade de Brasília - Instituto de Ciências Exatas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(111, 8, 365, 16);

        jLabel4.setText("Departamento de Ciência da Computação");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(163, 32, 260, 16);

        jLabel5.setText("Estrutura de dados - Turma B - Trabalho 1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(159, 56, 268, 16);

        jLabel6.setText("Avaliação de Expressões Aritméticas (forma posfixa)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(128, 80, 330, 16);

        jLabel8.setText("Prof. Eduardo A. P. Alchieri");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(209, 104, 168, 16);

        jLabel9.setText("Novembro 2012");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(243, 128, 101, 16);

        jLabel10.setText("Tiago Lage Payne de Pádua - 12/0142457");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(162, 173, 263, 16);

        jLabel11.setText("Alunos:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(269, 152, 48, 16);

        jLabel12.setText("Alex Leite");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(262, 194, 62, 16);

        jLabel13.setText("Ronaldo S. Ferreira Jr.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(226, 218, 134, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpressaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpressaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpressaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpressaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExpressaoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPosfixa;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtExpressao;
    // End of variables declaration//GEN-END:variables
}
